### ISSUE TITLE
Overworld Farm [Feature Request]

### ISSUE THREAD

**Issue by YTmaxord0076** [ReZeroE/StarRail#14]
Was thinking that autofarming the overworld might be the easiest thing to implement with amazing returns, you could easily have the script tp to teleporters and walk up to enemies and let them attack you, or attack them using the script using this route https://www.prydwen.gg/star-rail/guides/daily-farming-route
since farming this manually takes about an hour and a half

**Comment by ReZeroE** [comment]
@YTmaxord0076 Thanks for the suggestion. I'll look into this.

**Comment by MrTyton** [comment]
Is this actually supported? Or do we have to record it ourselves?

**Comment by ReZeroE** [comment]
@MrTyton No, auto-pathing is not supported as of version `1.0.5`.  Overworld farming needs to be recorded on an individual basis but the macros recorded can be shared between different machines that have the same `starrail` module version.
