### ISSUE TITLE
Can't use "starrail configure"  after pip install (Maybe i am just stupid.)

### ISSUE THREAD

**Issue by bagtokyoghoul1** [ReZeroE/StarRail#15]
as far as i know i installed all the needer prequesties for python. may also be that i am kind of dumb, since i am new with python, but can you please tell me why i possibly can't run it? 
![image](https://github.com/ReZeroE/StarRail/assets/102579159/4bd09842-4992-4777-a277-ac2c5f264973)
![image](https://github.com/ReZeroE/StarRail/assets/102579159/0dc008ce-41b5-4666-b2b0-9b21be8ee498)

**Comment by dolnic** [comment]
you are not the only one, maybe it is not available yet(I think)

**Comment by ShatteredGod** [comment]
same here

**Comment by soynoov** [comment]
![imagen_2024-03-03_020136276](https://github.com/ReZeroE/StarRail/assets/91479490/d72c78e9-d80f-4cb2-9bce-0505c920aaad)
Same
