### ISSUE TITLE
Curious

### ISSUE THREAD

**Issue by deadetou** [ReZeroE/StarRail#16]
Just curious. I know you're very busy and all, but will there be an eta on release date? Or is there a beta that can be pushed right now? Don't mean to sound conceited or impatient I'm really just curious. I need a material autofarmer and sim universe farmer bad lol

**Comment by ReZeroE** [comment]
Sorry for the late reply. The project has been completely revamped. See the updated [README ](https://github.com/ReZeroE/StarRail/blob/main/README.md) for more details.
