### ISSUE TITLE
mouse click doesn't work when in overworld map ("Star Rail Map")

### ISSUE THREAD

**Issue by 13lood** [ReZeroE/StarRail#19]
i am working on some custom code to choose one "world" to goto

but python can't click on herta/xianzhou/jarilo using pyautogui? 
any workaround to clickthrough?

**Comment by Dalfrak** [comment]
Try running your python app as admin, it worked for me ;)

**Comment by lordOsirisx** [comment]
> Try running your python app as admin, it worked for me ;)

hey boss can i have your assistance by chance do you have discord?
