### ISSUE TITLE
The script wont start.

### ISSUE THREAD

**Issue by MoogleMarket** [ReZeroE/StarRail#22]
Hey, i am currently on version 23.2.1.
i started the game with the command starrail start
the game startet but now i dont know what to do do start a script.
I dont see any overlay(I know its in dev. right now but in the setup thread i didnt find any commands or guides how i can use it.
[https://imgur.com/a/IzCvqRE](url)

**Comment by Lesser-Fullness** [comment]
Is the problem solved?

**Comment by MoogleMarket** [comment]
Sadly not, there was no update since 3 months.

**Comment by ReZeroE** [comment]
Sorry for the late reply. The project has been completely revamped with most of the features modified/changed. See the updated [README ](https://github.com/ReZeroE/StarRail/blob/main/README.md) for more details.
