### ISSUE TITLE
Error executing "starrail configure"

### ISSUE THREAD

**Issue by Antipov111** [ReZeroE/StarRail#26]
Error:
![изображение](https://github.com/user-attachments/assets/72b8c519-e377-4046-acb5-2ed930ef2681)

**Comment by ReZeroE** [comment]
Sorry, I developed the project in Python3.12 and completely neglected the updated f-string syntax in the newer Python versions. 

I've pushed out the newest update on PyPI with this issue fixed.

```
pip uninstall starrail
pip install starrail==1.0.1

starrail configure
```
This should work.

**Comment by Antipov111** [comment]
Thanks
