### ISSUE TITLE
Can you help me boss? I dont know how to install this, I tried everything but it didn't work for some reason

### ISSUE THREAD

**Issue by SrLikeGod** [ReZeroE/StarRail#35]

**Comment by SrLikeGod** [comment]
![Untitled](https://github.com/user-attachments/assets/c9a8513a-4b4e-4e9e-afa8-a615c8d1efe1)

**Comment by ReZeroE** [comment]
Hi there, not sure if you've already resolved the issue, but it appears that `pip` hasn't been added to your system's PATH. 

There's a few possible reasons to why this is happening, so I'd suggest that you checkout this video for help:
https://www.youtube.com/watch?v=dj5oOPaeIqI

After adding `pip` to PATH, try running
```
pip --version
```
to ensure its working. 

Let me know if theres anything else I can help with.
