### ISSUE TITLE
Pls answer

### ISSUE THREAD

**Issue by hAZEQUCIKIEE** [ReZeroE/StarRail#7]
hey how does this work i did everything alright with python but how it works i dont get it

**Comment by ReZeroE** [comment]
I can definitely help you with this. 

Currently, we are still in the process of implementing the automation features and the "easy-to-use" user interface for `starrail`. The command-line commands have been fully implmented but they only provide simple operations such as starting/stopping the game and configuring the module. The command-line commands are designed to be integrated with the UI in future updates and currently only provide an easy way to access the game.

Assuming that you finished installing Python 3, can you run the following commands in any terminal and show me the output just so that I can get a better idea of where you are at?

```
python --version
```

```
pip --version
```

**Comment by hAZEQUCIKIEE** [comment]
Python 3.11.3 
pip 23.1

**Comment by hAZEQUCIKIEE** [comment]
updated to 23.1.2

**Comment by ReZeroE** [comment]
Have you tried pip installing the module?

```
pip install starrail==0.0.3
```
OR
```
pip install starrail --upgrade
```
if you have already installed it.

Then to configure the package, run
```
starrail configure
```
Let me know if you have any problems getting to this point. After the configuration, please refer to the [Usage](https://github.com/ReZeroE/StarRail#usage) section in the README for more details.

**Comment by mayhemladygaga** [comment]
I get the error "'starrail' is not recognized as an internal or external command,
operable program or batch file."

**Comment by ReZeroE** [comment]
@sussydownloadanimegame 
Can you verify that the package has been successfully installed by running:
```
pip show starrail
```

***

If it says
```
WARNING: Package(s) not found: starrail
```
then you'll have to:
```
pip install starrail==0.0.3
```
If an error occurs during the process of running `pip install starrail==0.0.3`, please send the console output so that I can tell what's wrong.

Please let me know if this issue persists after trying the commands above.

**Comment by HonxY** [comment]
try adding python scripts folder to path in environment variables

**Comment by ReZeroE** [comment]
> try adding python scripts folder to path in environment variables

The `starrail` command is actually configured as a Python `console_script` entry point in `setup.cfg`. If the package is installed successfully, the `starrail` command should be directly registered as command-line accessible by the setuptools.

**Comment by ReZeroE** [comment]
The only two things that I can think of that might've caused the error
```
'starrail' is not recognized as an internal or external command,
operable program or batch file.
```
are that:

1. The package isn't successfully installed. 
2. The version of Python that installed the `starrail` module isn't in PATH (which is unlikely considering `pip` is called successfully). 

Anyhow, if anyone is encountering this problem, they should first check to see if the package is actually installed with `pip show starrail`.

If anyone has anything to add to this, please let me know.

**Comment by HonxY** [comment]
I had this problem, I did not have python in PATH, so i used py -m pip install starrail and when I used py -m pip show starrail it was  installed but starrail command didn't work in console. After adding python to PATH everything works, I can start the game no problem.
![resim_2023-05-04_120009000](https://user-images.githubusercontent.com/54810511/236158439-d6d5d095-4049-44fd-95ea-dd1e41e133c5.png)

**Comment by HonxY** [comment]
I had this problem, I did not have python in PATH, so i used py -m pip install starrail and when I used py -m pip show starrail it was  installed but starrail command didn't work in console. After adding python to PATH everything works, I can start the game no problem.
![resim_2023-05-04_120348390](https://user-images.githubusercontent.com/54810511/236159230-bc03370e-c745-48b5-8aab-7af54320fc07.png)

**Comment by hutigh** [comment]
What the script does for now ? It just start the game ? or i miss something

**Comment by ReZeroE** [comment]
@hutigh 

> What the script does for now ? It just start the game ? or i miss something

That's correct, only the basic command-line features are available right now. I'm the only developer who's actively working on this project at the moment and there's a lot of code to be written and a lot of testing to do before a release (with the UI, game logic, image/text recognition, and so on). Anyhow, I'm aiming to complete at least the basic auto-grind features (for Calyx) and the corresponding UI by next week.

**Comment by hutigh** [comment]
> 

Okay that's all good take your time i was just wondering if i was missing something on the current release haha 
Gl and cant wait to test that !

**Comment by paperc07** [comment]
Ok so I installed it and everything seemed to go smoothly I do the starrail start and it launches. But now what do I do to run it I don't see any commands or anything?

**Comment by hutigh** [comment]
If you go a little bit up this thread the creator explain that for now there is nothing more 



> @hutigh
> 
> > What the script does for now ? It just start the game ? or i miss something
> 
> That's correct, only the basic command-line features are available right now. I'm the only developer who's actively working on this project at the moment and there's a lot of code to be written and a lot of testing to do before a release (with the UI, game logic, image/text recognition, and so on). Anyhow, I'm aiming to complete at least the basic auto-grind features (for Calyx) and the corresponding UI by next week.

**Comment by paperc07** [comment]
oh ok well looking forward to this project

**Comment by hutigh** [comment]
> @hutigh
> 
> > What the script does for now ? It just start the game ? or i miss something
> 
> That's correct, only the basic command-line features are available right now. I'm the only developer who's actively working on this project at the moment and there's a lot of code to be written and a lot of testing to do before a release (with the UI, game logic, image/text recognition, and so on). Anyhow, I'm aiming to complete at least the basic auto-grind features (for Calyx) and the corresponding UI by next week.

Hello, i am just here to take some news ! :)
